### ISSUE TITLE
question about Lemmatize text

### ISSUE THREAD

**Issue by HaveF** [masci/banks#1]
Hi, 😄 

It's an interesting repo. `{# ... #}` comments is especially useful idea for me.

Btw, I have a question about `Lemmatize text while processing a template`, does this works better compare to original word format for LLMs?

**Comment by masci** [comment]
Hi @HaveF, thanks for stopping by!

I don't have benchmarks at hand, so while it's more or less a fact that lemmatization can help in several NLP tasks, I am not sure how much better an LLM works when the prompt is lemmatized.

In the context of prompt engineering, it's more the other way around: I use lemmatization to shrink the prompt and pay less money since I have less tokens, then the challenge is to verify the query is still effective. In my quite limited experiments I couldn't find a use case where a lemmatized prompt was giving back obviously wrong results, but your mileage might vary.

**Comment by HaveF** [comment]
thanks for your words!
